export const aboutFlowImages = [
  "/images/hero-office.png",
  "/images/services/website.jpg",
  "/images/services/website-b.jpg",
  "/images/services/website-c.jpg",
  "/images/services/software.jpg",
  "/images/services/software-b.jpg",
  "/images/services/software-c.jpg",
  "/images/services/app.jpg",
  "/images/services/app-b.jpg",
  "/images/services/app-c.jpg",
  "/images/hero-team.png",
  "/images/services/seo.jpg",
  "/images/services/seo-b.jpg",
  "/images/services/seo-c.jpg",
  "/images/services/smm.jpg",
  "/images/services/smm-b.jpg",
  "/images/services/smm-c.jpg",
  "/images/hero-visual.png",
  "/images/services/design.jpg",
  "/images/services/design-b.jpg",
  "/images/services/design-c.jpg",
  "/images/services/security.jpg",
  "/images/services/security-b.jpg",
  "/images/services/security-c.jpg",
  "/images/services/bugfix.jpg",
  "/images/services/bugfix-b.jpg",
  "/images/services/bugfix-c.jpg",
  "/images/welcome-hero.png",
] as const;

export const aboutFlowCopy = {
  flowWatermark: "Studio",
  flowTitle: "Inside the work",
  flowParagraphs: [
    "Real projects, real systems — from websites and software to brand, SEO, and growth.",
    "Scroll through the craft behind Jump If Zero.",
  ],
  flowCtaLabel: "Start a scoped engagement",
  flowCtaHref: "/contact",
} as const;
