import type {
  AdminBlogPost,
  AdminCallback,
  AdminClient,
  AdminContactMessage,
  AdminDemoState,
  AdminEmployee,
  AdminFaq,
  AdminFile,
  AdminInvoice,
  AdminLead,
  AdminLeadFollowUp,
  AdminMessage,
  AdminPortfolioItem,
  AdminProject,
  AdminSale,
  AdminSalesMessage,
  AdminService,
  AdminTeamMember,
  AdminSiteGalleryImage,
  AdminSiteTestimonial,
  AdminSitePrinciple,
  EmployeeKind,
  LeadStatus,
  SaleStatus,
} from "@/schemas/admin";

export type {
  AdminBlogPost,
  AdminCallback,
  AdminClient,
  AdminContactMessage,
  AdminDemoState,
  AdminEmployee,
  AdminFaq,
  AdminFile,
  AdminInvoice,
  AdminLead,
  AdminLeadFollowUp,
  AdminMessage,
  AdminPortfolioItem,
  AdminProject,
  AdminSale,
  AdminSalesMessage,
  AdminService,
  AdminTeamMember,
  AdminSiteGalleryImage,
  AdminSiteTestimonial,
  AdminSitePrinciple,
  EmployeeKind,
  LeadStatus,
  SaleStatus,
};

export const initialAdminDemoState: AdminDemoState = {
  services: [],
  portfolio: [],
  blog: [],
  faqs: [],
  team: [],
  employees: [],
  clients: [],
  projects: [],
  messages: [],
  invoices: [],
  files: [],
  callbacks: [],
  contactMessages: [],
  sales: [],
  leads: [],
  leadFollowUps: [],
  salesMessages: [],
  siteGallery: [],
  siteTestimonials: [],
  sitePrinciples: [],
};
