export const contactCopy = {
  title: "Start a scoped engagement.",
  lede: "Tell us what you are building, where it stands, and what “done” means. We reply with a clear next step — not a brochure.",
  responseTime: "Typical reply within 1–2 business days.",
  privacy: "We use this only to reply.",
  includeTitle: "What to include",
  includeItems: [
    "Goal and constraint (launch date, rebuild, acquisition, etc.)",
    "Current state (idea / live product / redesign)",
    "Stack or must-keep systems, if any",
    "Budget band or “need a range first”",
  ],
  directTitle: "Direct",
  emailLabel: "Email",
  phoneLabel: "Phone",
  emailCta: "Email a brief",
  phoneCta: "Call",
  messageTitle: "Send a message",
  messageSubmit: "Send message",
  callbackTitle: "Request a callback",
  callbackSubmit: "Request callback",
  formSuccess: "Thanks — we received your message and will reply soon.",
  formError: "Could not send your message. Try again or email us directly.",
  formValidationError: "Check the fields and try again.",
} as const;
